version: 2.1
orbs:
  node: circleci/node@5.2.0

jobs:
  test-js:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run:
          name: Setup Environment
          command: yarn && yarn install
      - run:
          name: Run tests
          command: yarn jest --reporters github-actions summary

  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt

  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"

workflows:
  example:
    jobs:
      - test-js
      - build:
          requires:
            - test-js
      - deploy:
          requires:
            - test-js
