version: 2.1
orbs:
  node: circleci/node@5.2.0

jobs:
  setup-js:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
          yarn-version: '1.22.22'
      - run:
          command: |
            corepack enable
            yarn set version 4.3.1
            yarn install

  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch example.txt
      - store_artifacts:
          path: example.txt

  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"

workflows:
  main:
    jobs:
      - setup-js
      - node/test:
          requires:
            - setup-js
          test-results-for: jest
          pkg-manager: yarn
      - build:
          requires:
            - node/test
      - deploy:
          requires:
            - node/test
